Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 10.60.129.61:3306
  DBName: loki
  TablePrefix: Loki_
  Charset: utf8
  Parsetime: True
  MaxIdleConns: 10
  MaxOpenConns: 10

JWT:
  Secret: loki-Secret
  Issuer: loki-service
  Expire: 7200