Server:
  RunMode: debug
  HttpPort: 10900
  ReadTimeOut: 60
  WriteTimeOut: 60

Database:
  DBType: mysql
  #  Host: 10.60.129.61:3306
  #  Username: root
  #  Password: 123456
  Host: 10.61.153.77:3306
  Username: adminm
  Password: adminm
  DBName: odin-inner
  TablePrefix: Loki_
  Charset: utf8
  Parsetime: True
  MaxIdleConns: 10
  MaxOpenConns: 10
  LogModeBool: true

JWT:
  Secret: loki-Secret
  Issuer: loki-service
  Expire: 604800

Logrus:
  Log_FILE_PATH: log
  LOG_FILE_NAME: loki